# data
dev_qrel_path: ./data/marco/dev.small.qrel.tsv
dev_data_path: ./data/marco/dev.small.tsv

train_data_path: ./data/marco/train.tsv
test_data_path: ./data/marco/test.tsv
test_qrel_path: ./data/marco/qrel.tsv

prediction_output_path: ./results/marco/predictions/
model_save_path: ./model_saved/marco/{}_Stage{}_Epoch{}.pth

forgetting_samples_path: ./data/marco/forgetting_samples.pkl
forgetting_substitute_samples_path: ./data/marco/forgetting_substitute_samples.pkl
dataset_name: msmarco
