

# vocab
vocab_path: /home/lunet/cojh6/Documents/machine_unranking/word-vocab-glove.tsv
# word2vec
embed: /home/lunet/cojh6/Documents/machine_unranking/glove.6B.300d.txt
embed_dim: 300
unk_token: 0


# model
seed: 10
NUM_HIDDEN_NODES: 300
POOLING_KERNEL_WIDTH_DOC: 100
TERM_WINDOW_SIZE: 3
DROPOUT_RATE: 0.5
query_max_len: 20
target_max_len: 200
batch_size: 1024
prediction_batch_size: 1024
distil_batch_size: 32
epochs: 5
distil_epochs: 20
# learning_rate: 0.001 # for doc removal
# embedding_learning_rate: 0.00001 # for doc removal
# distil_learning_rate: 0.00007 # for doc removal
learning_rate: 0.0001
embedding_learning_rate: 0.000005
distil_learning_rate: 0.00005
model_type: duet
model_name: DUET
freeze_d_emb: False
freeze_q_emb: False
q_d_emb_same: True
need_local_feature: True
local_idf_file: /home/lunet/cojh6/Documents/machine_unranking/idfnew.norm.tsv

# distillation_margin: 0 # for doc removal
# distillation_ratio: 0.01 # for doc removal
distillation_margin: 0.1
distillation_ratio: 0.05
