# vocab
vocab_path: /home/lunet/cojh6/Documents/machine_unranking/word-vocab-glove.tsv
# word2vec
embed: /home/lunet/cojh6/Documents/machine_unranking/glove.6B.300d.txt
embed_dim: 300
unk_token: 0

# model
seed: 10
n_kernels: 11
query_max_len: 20
target_max_len: 200
batch_size: 32
epochs: 20
learning_rate: 0.00005
out_kernel: 64
max_grams: 3

model_type: cknrm
model_name: CKNRM
freeze_d_emb: False
freeze_q_emb: False
